name: flutter_application_1
description: 'Flutter News App using MVVM'

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.0.1

  # Add sqflite for SQLite database operations
  sqflite: ^2.2.0

  # Add path for handling file paths
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
